### ISSUE TITLE
Bioconductor?

### ISSUE THREAD

**Issue by jsicherman** [jsicherman/GemmAPI#10]
Bioconductor seems to be pretty stringent about the code requirements (based on a quick look at the failing Actions)... They also don't allow non-CRAN/Bioconductor packages (`async` would then not qualify, and it's used pretty centrally...)

CRAN would be a much easier sell... Thoughts @yavyx ?

**Comment by yavyx** [comment]
I personally see the value in publishing in Bioconductor where I think it would get more users and attention than in CRAN, and I wouldn't mind changing the code to fit their requirements (it seems like mostly style changes) but there are other bigger issues Bioconductor. I'll summarize the three options that I think we have:

1. Publish on CRAN with no support for Bioconductor data structures. This is the easiest and we'd almost be ready to publish.

2. Publish on CRAN while supporting Biocondutcor data structures, like Ogan suggested. This could work but I have not figured out a way of getting Bioconductor packages to play nice with the standard R Package Github actions workflow (and [it's not easy to do so](https://github.com/r-lib/actions/issues/84)) unless we use the Bioconductor-specific workflow that doesn't allow `async`, which brings us to #3.

3. Embed the `async` package into ours and publish on Bioconductor, I emailed Gabor Csardi asking him about this issue. He's not planning to publish `async` on CRAN soon but suggested we could embed `async` into our package like [this](https://github.com/r-lib/pkgcache/blob/master/R/aaa-async.R).

 @jsicherman

**Comment by jsicherman** [comment]
If you/Paul/Ogan see the value in Bioc then I say we should go for it. Embedding `async` is a cool possibility that I didn't really know about. My understanding is that you shouldn't double publish to both CRAN and Bioc so let's just drop CRAN then. Action items should then be:

1. Embed `async` into `gemmaAPI` (preferably this gets injected automatically in `registry.R` so that we don't have to re-download updates, but that would be fine too if it doesn't update often)
2. Stylistic changes to fit Bioconductor requirements. See the output [here](https://github.com/jsicherman/GemmAPI/runs/3080701802?check_suite_focus=true#step:25). Can possibly pass all the code through [styler](https://github.com/r-lib/styler) to do this automatically.
3. Remove the R CMD CHECK action (I think)
4. Fix badges on `README.Rmd` to reflect Bioc instead of CRAN

**Comment by jsicherman** [comment]
Made a branch for this with some preliminary work: https://github.com/jsicherman/GemmAPI/tree/bioconductor-wip

Addresses badges (partially), and embedding `async`. There are some warnings to do with imports being wonky; I didn't inspect these too much yet. Seems like the embedding worked, though.
