### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by jsicherman** [jsicherman/GemmAPI#5]
{testthat} should be used to make sure that the parsed results are not inaccurate. My initial implementation was pretty quick and I wouldn't be surprised if at least a couple endpoints parse in weird and unexpected ways.

**Comment by jsicherman** [comment]
Something worth testing while you're writing these @yavyx is that the results when `raw = T` and `raw = F` are in mutual agreement.

Something like
```
expect_equal(getDatasetDEA(1)[, paste0(cf.Cat, cf.Baseline, cf.Val, collapse = '')],
             getDatasetDEA(1, raw = T)$resultSets[[1]]$experimentalFactors[[1]]$values[[1]][, c('factorValue', 'value')] %>% { paste0(.[2, 2], .[2, 1], .[1, 1], collapse = '') })
```

But better. This way we know that the result parsing is working as expected

**Comment by jsicherman** [comment]
I might add some tags to the `*Info` functions and `mem*` functions at some point so that the codecov report doesn't look so dismal

**Comment by yavyx** [comment]
Sounds good, but most of the untested code is in the CategoryEndpoints which we might remove later
