### ISSUE TITLE
Numerical inputs to getGenes

### ISSUE THREAD

**Issue by yavyx** [jsicherman/GemmAPI#9]
getGenes accepts multiple gene ID's as input, but it doesn't accept multiple numerical inputs. getDatasets uses the same validator and does accept multiple numerical inputs.

```r
getGenes(c('1','2'))  # works
getGenes(c(1, 2))  # doesn't work
getDatasets(c(1, 2)) # works
```

**Comment by jsicherman** [comment]
Should be fixed in 470df61
